
set(TARGET_SOURCES_DIR "Private")
set(TARGET_HEADERS_DIR "Public")

file(GLOB_RECURSE TARGET_SOURCES
    "${TARGET_SOURCES_DIR}/*.cpp")

file(GLOB_RECURSE TARGET_HEADERS
    "${TARGET_HEADERS_DIR}/*.h" "${TARGET_SOURCES_DIR}/*.h")

mark_as_advanced(
    TARGET_HEADERS 
    TARGET_SOURCES 
    TARGET_HEADERS_DIR 
    TARGET_SOURCES_DIR
)
