if (WIN32)
    add_compile_definitions(PLATFORM_WINDOWS)
elseif (APPLE)
    add_compile_definitions(PLATFORM_APPLE)
    add_compile_definitions(WITH_MOLTEN_VK)
else()
    message(FATAL_ERROR "Unknown platform")
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    add_compile_definitions(_64_BIT)
else()
    add_compile_definitions(_32_BIT)
endif()
